require('nvim-lua-config/plugin_config/lualine')
require('nvim-lua-config/plugin_config/nvim-tree')
require('nvim-lua-config/plugin_config/treesitter')
require('nvim-lua-config/plugin_config/gruvbox')
require('nvim-lua-config/plugin_config/treesitter')
